services:
  transactions:
    build:
      context: .
      dockerfile: ./services/transactions/Dockerfile
      target: development
    command: npm run dev:transactions
    env_file:
      - ./.env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
      target: development
    command: npm run dev:auth
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  balance:
    build:
      context: .
      dockerfile: ./services/balance/Dockerfile
      target: development
    command: npm run dev:balance
    env_file:
      - ./.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
